### ISSUE TITLE
Problem with CADoCommand with parameters

### ISSUE THREAD

**Issue by WillyAguilera1977** [JoseRoca/WinFBX#10]
I have a problem with a program that uses CADOCommand objects with Parameters.
It gives me an error in the Value property of the parameter object. Y
also with the Append method of the Parameters collection.
It doesn't compile and shows the following message:
EX_CADO_Command_Execute.bas(89) error 99: No matching overloaded function, VALUE() in 'param.Value = v1'

EX_CADO_Command_Execute.bas(90) error 3: Expected End-of-Line, found 'Append' in 'cmd.Parameters.Append param

Here is the complete code:

' Edit this constant to match your directory structure.
Const DBPATH = "NWind.mdb"
Dim cmd As CADOCommand  ' , rs As CADORecordset

cmd.CommandType = adCmdText
cmd.CommandText = "Select * From Employees Where BirthDate > ? " _
    & "AND HireDate > ?"
cmd.ActiveConnection = "Provider=Microsoft.Jet.OLEDB.4.0;" _
    & "Data Source= " & DBPATH
' You can use a temporary Parameter variable.

Dim As Double v1, v2
Dim As String  s1, s2

s1 = "1/1/1960"

s2 = "1/1/1993"

' convert the strings to date serials
v1 = DateValue( s1 )
Print v1
Print
Print

v2 = DateValue( s2 )
Print v2

Dim param As CADOParameter = cmd.CreateParameter("BirthDate", adDate, adParamInput, 0)
'Dim valor As CVar = v1

'param.Value = v1
cmd.Parameters.Append param

'Dim rs As CAdoRecordset = cmd.Execute

'param = cmd.CreateParameter("BirthDate", adDate, adParamInput)
'param->Value= v1
'parameter = Command.CreateParameter (Name, Type, Direction, Size, Value)

' // Parse the recordset
''Do
''	' // While not at the end of the recordset...
''	If rs.EOF Then Exit Do
''	' // Get the content of the "Author" column
''	'   DIM cvRes AS CVAR = pRecordset.Collect("Author")
''	'   PRINT cvRes
''	Print rs.Collect("Nombre")
''	
''	Print rs.Collect("Apellidos")
''	
''	'Print rs.Collect("Year Born")
''	
''	' // Fetch the next row
''	If rs.MoveNext <> S_OK Then Exit Do
''Loop

Print
Print "Press any key..."
Sleep

What do I have to do to correct it?

Thank you very much in advance

**Comment by JoseRoca** [comment]
Sorry for the delay.

> EX_CADO_Command_Execute.bas(89) error 99: No matching overloaded function, VALUE() in 'param.Value = v1'

It works with FB 1.07. I haven't yet tested the latest compilers.

> EX_CADO_Command_Execute.bas(90) error 3: Expected End-of-Line, found 'Append' in 'cmd.Parameters.Append param

This VB like compound syntax isn't supported by FB. You have to use:

DIM params AS CADOParameters = cmd.Parameters
params.Append(param)

**Comment by WillyAguilera1977** [comment]
Thanks for your reply, I managed to solve the problem. 
But I have another problem with date literals, they don't exist in FreeBasic. I opened a new issue. see it, please.
