### ISSUE TITLE
how to translate this program in Visual Basic 6.0 to FreeBasic

### ISSUE THREAD

**Issue by WillyAguilera1977** [JoseRoca/WinFBX#11]
I need to translate this program from Visual Basic 6.0 to FreeBasic. The problem is date literals that don't exist in FreeBasic.
What do I have to do.
Thanks very much in advance.

' Edit this constant to match your directory structure.
Const DBPATH = "C:\Program Files\Microsoft Visual Studio\Vb98\NWind.mdb"
Dim cmd As New ADODB.Command, rs As New ADODB.Recordset
cmd.CommandText = "Select * From Employees Where BirthDate > ? " _
    & "AND HireDate > ?"
cmd.ActiveConnection = "Provider=Microsoft.Jet.OLEDB.4.0;" _
    & "Data Source= " & DBPATH
' You can use a temporary Parameter variable.
Dim param As ADODB.Parameter
Set param = cmd.CreateParameter("BirthDate", adDate, , , #1/1/1960#) ' this is the problem date literals
cmd.Parameters.Append param
' Or you can do everything in one operation. 
cmd.Parameters.Append cmd.CreateParameter("HireDate", adDate, , , _
    #1/1/1993#)
Set rs = cmd.Execute(, , adCmdText)
Waiting for your answer, I greet you very sincerely

**Comment by JoseRoca** [comment]
Instead of passing a date literal, try

DIM cvDate AS CVAR
cvDate.PutDateString("1/1/1960")

and pass cvDate.

**Comment by WillyAguilera1977** [comment]
I still can't find the solution to the date problem.
The code below causes an infinite loop.
What am I wrong?
Here is the code that I have already done
What should I correct?




' Edit this constant to match your directory structure.
Const DBPATH = "NWind.mdb"
Dim cmd As CADOCommand  ' , rs As CADORecordset

cmd.CommandType = adCmdText
cmd.CommandText = "Select * From Empleados Where FechaNacimiento > ? " _
    & "AND FechaContratación > ?"
cmd.ActiveConnection = "Provider=Microsoft.Jet.OLEDB.4.0;" _
    & "Data Source= " & DBPATH
' You can use a temporary Parameter variable.


'

Dim cvDate As CVAR
cvDate.PutDateString("1/1/1960")

Dim param As CADOParameter = cmd.CreateParameter("FechaNacimiento", adDate, adParamInput, , cvDate)


'param.Value = cvDate

Dim cvDate2 As CVAR
cvDate2.PutDateString("1/1/1993")
'
Dim param2 As CADOParameter = cmd.CreateParameter("FechaContratacion", adDate, adParamInput, , cvDate2)
'
'param2.Value = cvDate2
'
Dim params As CADOParameters = cmd.Parameters
params.Append(param)
params.Append(param2)
'
Dim rs As CAdoRecordset = cmd.Execute
'Print rs.RecordCount

' Parse the recordset
Do
	' // While not at the end of the recordset...
	If rs.EOF Then Exit Do
	
	Print rs.Collect("Nombre")
	
	Print rs.Collect("Apellidos")
	
	' // Fetch the next row
	If rs.MoveNext <> S_OK Then Exit Do
Loop

Print
Print "Press any key..."
Sleep

Waiting for your answer, I greet you very sincerely

**Comment by JoseRoca** [comment]
I don't see nothing wrong, but you don't do any error checking.
Each object has a GetlastResult method.
print cmd.GetLastResult after cmd.CreateParameter
and so on.

**Comment by WillyAguilera1977** [comment]
Hello again.
I did what you told me.
I got the error code through cmd.GetLastResult after cmd.CreateParameter: Gives an HRESULT of 0, that is, S_OK.
Also when executing the following line of code:
Dim rs As CAdoRecordset = cmd.Execute. Gives an error:
-2147217904 . In hexadecimal it is 80040E10.
Searching on the internet I got the OLEDB Error codes. The error is: No value given for one or more required parameters.

// OLEDB Error codes
// MessageId: DB_E_PARAMNOTOPTIONAL
// MessageText:
// No value given for one or more required parameters.

DB_E_PARAMNOTOPTIONAL = unchecked((int)0x80040E10),

I don't know what to do, according to me I pass the parameters well

Here I show you the code again:

' Edit this constant to match your directory structure.
Const DBPATH = "NWind.mdb"
Dim cmd As CADOCommand  ' , rs As CADORecordset

cmd.CommandType = adCmdText
cmd.CommandText = "Select * From Employees Where BirthDate > ? " _
    & "AND HireDate > ?"
cmd.ActiveConnection = "Provider=Microsoft.Jet.OLEDB.4.0;" _
    & "Data Source= " & DBPATH
' You can use a temporary Parameter variable.

Dim cvDate As CVAR
cvDate.PutDateString("1/1/1960")

Dim param As CADOParameter = cmd.CreateParameter("BirthDate", adDate, adParamInput, , cvDate)

Print "Resultado 1: ", cmd.GetLastResult

Sleep
'param.Value = cvDate

Dim cvDate2 As CVAR
cvDate2.PutDateString("1/1/1993")
'
Dim param2 As CADOParameter = cmd.CreateParameter("HireDate", adDate, adParamInput, , cvDate2)
'
'param2.Value = cvDate2

Print "Resultado 2: ", cmd.GetLastResult
Sleep
'

Dim params As CADOParameters = cmd.Parameters
params.Append(param)
params.Append(param2)
params.Refresh

Print "Result 3 Append: ", cmd.GetLastResult 'Result =0 . S_OK

Sleep
'
**Dim rs As CAdoRecordset = cmd.Execute

Print "Result 4 Execute:", cmd.GetLastResult    =  Result in this  '       -2147217904       80040E10**

Sleep

' Parse the recordset
Do
	' // While not at the end of the recordset...
	If rs.EOF Then Exit Do
	' // Get the content of the "Author" column
	'   DIM cvRes AS CVAR = pRecordset.Collect("Author")
	'   PRINT cvRes
	Print rs.Collect("FirstName")
	
	Print rs.Collect("LastName")
	
	' // Fetch the next row
	If rs.MoveNext <> S_OK Then Exit Do
Loop

Print
Print "Press any key..."
Sleep

**Comment by WillyAguilera1977** [comment]
Hello again. I solved the problem. It was my mistake. I wrote it wrong. Thank you very much for the help. I congratulate you for the framework is wonderful.
