### ISSUE TITLE
object position values issue from visually impaired man

### ISSUE THREAD

**Issue by JanuszChmiel** [JoseRoca/WinFBX#6]
Dear MR Roca,
Because I do not see at all, I Am forcing to use FNX Basic language which is for now very probably The only one language, which I can use even to create complex GUIS without adding object position values for every GUI element.
Unfortunately, Microsoft have issues with .exes which have been compiled by this language and Windows defender classify those apps as An virus, which is wrong, false positive.
But actually, I AM helpless to distribute my free apps compiled by FNX Basic thanks to The Microsoft antivirus polici.
So I must use Free Basic, since Rapidq do not allow Me to use Unicode characters when creating listboxes and other GUI elements. Czech characters are misinterpreted.
Do you think, that it would be extremely complex for you to extend yours library so visually impaired programmers would use it without adding object position values?
So library would had to contain some auto formatting routine, which would place every object on The screen when app will be run.
Even Rapidq allow users to use adjectives to specify object positions.
altop
alclient
alcenter
ETC.
Which complex mathematic formulas would had to be added to yours library so GUi would be also created by visually impaired users?

Powerbasic also enforces number position values. BLind programmer can not correctly determine The values, because he can not see on The screen how to adjust those values so GUI elements will be acceptable.

And powerful Microsoft will very probably never change their antivirus polici.
Autohodkey compiled apps, Autoid and FNX Basic will be always analysed by Windows defender as suspicious apps, which even increase The time before app is being loaded.
Powerbasic apps, Free Basic apps, Pure Basic apps are not classified as so suspicious ones.
If you would help Me, please let me know. I AM ready to test.
If you know about Free Basic module, which would allow Me to design GUi without number position values, please let Me know about it.
With deepest appreciation and with The warmest regards.
Janusz Chmiel

**Comment by networkproblemsolver** [comment]
Actually, I've had AV programs reject PowerBASIC programs as malware for decades now.  Another reason why I switched to FreeBasic.

**Comment by JanuszChmiel** [comment]
And what do you think, about .inc module development, which would allow
programmers to design GUI wšith no need to specify object position values?
Sure, sighted people can use visual designers. Or it would had to contain
some complex mathematical formulas wihch would automatically calculate
object positions in run time and it would be too complex?
Borland have developed VCL unit for Borland Delphi 7.0. So it is possible.
But The question is how complex it would be to develop similar routines from
scratch.
I have spent many many hours while searching various Free Basic ccompatible
GUI units, but every unit require object position values to be typed from
source code as parameter.

**Comment by JanuszChmiel** [comment]
I will give you a little app example compatible with FNX Basic, which is
based on Borland Delphi and VCL Borland unit.
As A result, even I do not see at all, I can simply create GUI by typing The
following commands without add value to spcify GUi element position in
Pixels or by using other value unit.
object myform as form
  center
caption="GUI example"
  object mylist as listbox
    align=alleft
    additem("1")
additem ("2")
    onclick=mylistbox_click
  end object
myform.showmodal
sub mylistbox_click(s as listbox)
vv =s.itemindex 
end sub
I can react on lite item focused and selected by typing case slect vv of

Do you think, that there would be some Free Basic community developer, who
would try to create similar simple GUi creation unit? Or it would require
too much time to develop?

**Comment by JoseRoca** [comment]
Sorry, but my framework is low-level, not object oriented. In the clasic Windows way, you recive messages in the window callback procedure, not onclick or similar events. The GUI wrappers for controls call directly the Windows API and don't have properties. Maybe you could use Paul Squire's WinFormsX without the visual designer, although he may need to make many changes.

**Comment by JanuszChmiel** [comment]
Thank you very much for yours explanation. I will be using FNX Basic. I have
searched for many languages but there is no something similar.
Thank you very much for yours time and for yours programmers work.
I know, that automatic GUI formatting is very complex. This is The reason,
why Borland Delphi was and is still so expensive.
