### ISSUE TITLE
cursor format support of AfxGdiplus.inc

### ISSUE THREAD

**Issue by elfsimulate** [JoseRoca/WinFBX#9]
hi, I'm newer of freebasic ,first of all, thanks to Jose's work , it's a great job of WinFBX.
it's a problem ocurrs to me that when I use AfxGdipBitmapFromFile function to load a cursor file to a image control, it seems not work, but the icon file can be loaded. I checked the source code of AfxGdiplus.inc finding that AfxGdipBitmapFromFile function is finally calling AfxGdipImageFromBuffer to do the work, it  seems to be not calling successfully for dealing with cursor file. I do not know how to fix it, is it a bug or just a wrong of my coding?
[yGDI.txt](https://github.com/JoseRoca/WinFBX/files/5922705/yGDI.txt)

**Comment by JoseRoca** [comment]
As far as I know, GDI+ doesn't support cursor files.

**Comment by elfsimulate** [comment]
> 
> 
> As far as I know, GDI+ doesn't support cursor files.

ok，thx，let me try to fix it
